name: mediclo EHR Service Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 버전 정보 추출
      run: echo "##[set-output name=version;]$(echo '${{ github.event.head_commit.message }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"
      id: extract_version_name       
    - name: 변수확인
      run: echo ${{ steps.extract_version_name.outputs.version }}
    - name: Create tag
      run: |
        git config --local user.email "shjhwoo@trustnhope.com"
        git config --local user.name "shjhwoo"
        git tag "v${{ steps.extract_version_name.outputs.version }}"
        git push --tags